### ISSUE TITLE
error 403 kinetic-v4.7.min.js 

### ISSUE THREAD

**Issue by rsenthilkumar6** [JamieWohletz/easynote#1]
GET http://d3lp1msu2r81bx.cloudfront.net/kjs/js/lib/kinetic-v4.7.4.min.js 403 (Forbidden)

downloaded and tried to open facing the issue.

**Comment by JamieWohletz** [comment]
Thanks for letting me know! I actually haven't supported this project in years, so I'd suggest forking it and fixing the issue if you wish to use it. Honestly, it's using a bunch of outdated practices, so I'd recommend finding something else. 

Cheers! 
Jamie
